---

- name: create usernames
  set_fact:
    _ocp4_workload_ama_demo_app_services_shared_users: |
       {{ _ocp4_workload_ama_demo_app_services_shared_users | default([]) + [ocp4_workload_ama_demo_app_services_shared_user_prefix+item | string] }}
  loop: "{{ range(1,((ocp4_workload_ama_demo_app_services_shared_user_count | int) + 1)) | list }}"

- name: "create {{ ocp4_workload_ama_demo_app_services_shared_user_count }} namespaces for bookbag"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'bookbag/namespace-bookbag.yaml.j2') }}"
  vars:
    _ocp4_workload_ama_demo_app_services_bookbag_shared_namespaces:
      - "{{ ocp4_workload_ama_demo_app_services_shared_bookbag_namespace_prefix }}user"
  retries: 10
  delay: 30

- name: deploy applicationset
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'bookbag/applicationset-bookbag.yaml.j2' ) | from_yaml }}"
