---

- name: Set user variables
  set_fact:
    _ocp4_workload_ama_demo_app_services_shared_user: >-
      {{ ocp4_workload_ama_demo_app_services_shared_user_prefix }}{{ n }}

- name: Set Namespace variables
  set_fact:
    _ocp4_workload_ama_demo_app_services_shared_namespace: >-
      {{ ocp4_workload_ama_demo_app_services_shared_namespace_prefix }}{{ _ocp4_workload_ama_demo_app_services_shared_user }}

- name: Setup Bookbag for user
  include_role:
    name: ocp4_workload_bookbag_user
  vars:
    globex_ui_route: "{{ r_globex_ui_route.resources[0] }}"
    activity_tracking_simulator_route: "{{ r_activity_tracking_simulator_route.resources[0] }}"
    ocp4_workload_bookbag_user_project: "bookbag-{{_ocp4_workload_ama_demo_app_services_shared_user}}"
    ocp4_workload_bookbag_user_project_display: "Bookbag for user {{ _ocp4_workload_ama_demo_app_services_shared_user }}"
    ocp4_workload_bookbag_user_image_namespace: bookbag
    ocp4_workload_bookbag_user_image_name: >-
      image-registry.openshift-image-registry.svc:5000/{{ ocp4_workload_bookbag_user_image_namespace }}/bookbag
    ocp4_workload_bookbag_user_image_tag: latest
    ocp4_workload_bookbag_user_console_deploy: false
    ocp4_workload_bookbag_user_custom_workshop_vars:
      user: "{{ _ocp4_workload_ama_demo_app_services_shared_user }}"
      user_password: "{{ ocp4_workload_authentication_htpasswd_user_password }}"
      openshift_cluster_console: "https://{{ r_console_route.resources[0].spec.host }}"
      globex_ui_url: >-
        https://globex-ui-{{ _ocp4_workload_ama_demo_app_services_shared_namespace }}.{{ r_route_subdomain }}
      activity_tracking_simulator_url: >-
        https://activity-tracking-simulator-{{ _ocp4_workload_ama_demo_app_services_shared_namespace }}.{{ r_route_subdomain }}
