---

- name: Install AMQ Streams Operator
  when: ocp4_workload_ama_demo_app_services_shared_lab_setup | bool
  ansible.builtin.include_tasks: amq_streams_operator.yml

- name: Install Service Binding Operator
  when: ocp4_workload_ama_demo_app_services_shared_lab_setup | bool
  ansible.builtin.include_tasks: service_binding_operator.yml

- name: Set up app services lab - common
  when: ocp4_workload_ama_demo_app_services_shared_lab_setup | bool
  ansible.builtin.include_tasks: setup-app-services-lab-common.yml

- name: Set up app services lab - gitops
  when: ocp4_workload_ama_demo_app_services_shared_lab_setup | bool
  ansible.builtin.include_tasks: setup-app-services-lab-gitops.yml

- name: Set up app services lab - bookbag gitops
  when:
    - ocp4_workload_ama_demo_app_services_shared_lab_setup | bool
    - ocp4_workload_ama_demo_app_services_shared_bookbag | bool
  ansible.builtin.include_tasks: setup-app-services-lab-bookbag.yml
