---
# Implement your Post Workload deployment tasks here
- name: output workshop info
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
    - ""
    - "Day In the Life - {{ ocp4_workload_dil_serverless_lab_title }} provisioned for {{ num_users }} user(s)"
    - ""
    - "User Registration: https://users-registration.{{ route_subdomain }}"
    - "Access Token for registration is '{{ ocp4_workload_dil_serverless_user_access_token }}'"
    - "You should share this URL (or a shortlink for it) -- It is all they will need to get started!"
    - ""
    - "Solution Explorer: "
    - "https://{{ webapp_secure_route }}"
    - ""
    - "OpenShift Console: {{ console_url }}"
    - "Cluster admin login with '{{ ocp_username }}' / 'r3dh4t1!'"
  when: not silent|bool

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
