---
- name: Provision Operator Snapshot
  include_tasks: provision_snapshotoperator.yaml
  vars:
    snapshot_operator_project: "openshift-marketplace"

- name: Provision AMQ Streams
  include_tasks: provision_streams.yaml
  vars:
    operators_project: "openshift-operators"
    snapshot_operator_project: "openshift-marketplace"

- name: Provision Serverless
  include_tasks: provision_serverless.yaml
  vars:
    operators_project: "openshift-operators"
    snapshot_operator_project: "openshift-marketplace"
    shared_kafka_project: "kafka"

- name: Provision Web Terminal
  include_tasks: provision_terminal.yaml
  vars:
    operators_project: "openshift-operators"
    snapshot_operator_project: "openshift-marketplace"

- name: Provision Camel K
  include_tasks: provision_camelk.yaml
  vars:
    operators_project: "openshift-operators"
    snapshot_operator_project: "openshift-marketplace"

- name: Provision API Designer
  include_tasks: provision_designer.yaml
  vars:
    apicurito_project: "designer"
    snapshot_operator_project: "openshift-marketplace"
  when: 
    - cloud_provider is defined
    - cloud_provider != "azure"

- name: Provision Managed Services
  include_tasks: provision_managed.yaml
  vars:
    operators_project: "openshift-operators"
    snapshot_operator_project: "openshift-marketplace"

- name: Provision Skupper Interconnect
  include_tasks: provision_skupper.yaml
  vars:
    operators_project: "openshift-operators"
    snapshot_operator_project: "openshift-marketplace"

- name: Provision OpenShift Container Storage
  include_tasks: provision_ocs.yaml
  vars:
    ocs_project: "openshift-storage"
    snapshot_operator_project: "openshift-marketplace"

# - name: Provision Shared Resources
#   include_tasks: provision_shared.yaml
#   vars:
#     db_earth_namespace: "shared-db-earth"
#     kafka_earth_namespace: "shared-kafka-earth"
#     app_earth_namespace: "shared-app-earth"

- name: Provision Solution Explorer
  include_tasks: provision_instructions.yaml
  vars:
    webapp_namespace: "instructions"
  when: 
    - cloud_provider is defined
    - cloud_provider != "azure"

- name: Provision User Registration
  include_tasks: provision_registration.yaml
  vars:
    registration_namespace: "registration"
  when: 
    - cloud_provider is defined
    - cloud_provider != "azure"

- name: Provision {{ num_users }} User Namespaces
  include_tasks: provision_userprojects.yaml

- name: Provision Code Ready Workspace
  include_tasks: provision_crw.yaml
  vars:
    che_project: "codeready"
    snapshot_operator_project: "openshift-marketplace"
  when: 
    - cloud_provider is defined
    - cloud_provider != "azure"
